Fix 'Travis CI' build failures
ibab/tensorflow-wavenet pull request #399
Opened 2020-10-04 05:17 UTC by ashahba

2020-10-04 06:26 UTC, ashahba commented
@ibab I'm not sure how maintains this repository now.
Would you please review and let me know if there are any feedback?

Thanks.

2021-09-18 15:08 UTC, SerafimC commented
It´s sad that the author does not maintains this repository anymore. Is it possible to add new reviewers that could aprove these changes?

2021-10-09 15:05 UTC, KaheriB approved these changes

2021-10-09 15:06 UTC, KaheriB requested changes
V

2021-12-23 20:07 UTC, neko-is-kitty commented
> It´s sad that the author does not maintains this repository anymore. Is it possible to add new reviewers that could aprove these changes?

Heyo @SerafimC, I would write to @ibab directly. Their email is in their profile, so it wouldn't hurt to try

2025-06-29 07:14 UTC, closed without merging